/** HTML tag-to-DOM-type map from TypeScript's `lib.dom.d.ts`, deprecated tags included. */
const tag_map = {
  a: "HTMLAnchorElement",
  abbr: "HTMLElement",
  address: "HTMLElement",
  applet: "HTMLUnknownElement",
  area: "HTMLAreaElement",
  article: "HTMLElement",
  aside: "HTMLElement",
  audio: "HTMLAudioElement",
  b: "HTMLElement",
  base: "HTMLBaseElement",
  basefont: "HTMLElement",
  bdi: "HTMLElement",
  bdo: "HTMLElement",
  bgsound: "HTMLUnknownElement",
  blink: "HTMLUnknownElement",
  blockquote: "HTMLQuoteElement",
  body: "HTMLBodyElement",
  br: "HTMLBRElement",
  button: "HTMLButtonElement",
  canvas: "HTMLCanvasElement",
  caption: "HTMLTableCaptionElement",
  cite: "HTMLElement",
  code: "HTMLElement",
  col: "HTMLTableColElement",
  colgroup: "HTMLTableColElement",
  data: "HTMLDataElement",
  datalist: "HTMLDataListElement",
  dd: "HTMLElement",
  del: "HTMLModElement",
  details: "HTMLDetailsElement",
  dfn: "HTMLElement",
  dialog: "HTMLDialogElement",
  dir: "HTMLDirectoryElement",
  div: "HTMLDivElement",
  dl: "HTMLDListElement",
  dt: "HTMLElement",
  em: "HTMLElement",
  embed: "HTMLEmbedElement",
  fieldset: "HTMLFieldSetElement",
  figcaption: "HTMLElement",
  figure: "HTMLElement",
  font: "HTMLFontElement",
  footer: "HTMLElement",
  form: "HTMLFormElement",
  frame: "HTMLFrameElement",
  frameset: "HTMLFrameSetElement",
  h1: "HTMLHeadingElement",
  h2: "HTMLHeadingElement",
  h3: "HTMLHeadingElement",
  h4: "HTMLHeadingElement",
  h5: "HTMLHeadingElement",
  h6: "HTMLHeadingElement",
  head: "HTMLHeadElement",
  header: "HTMLElement",
  hgroup: "HTMLElement",
  hr: "HTMLHRElement",
  html: "HTMLHtmlElement",
  i: "HTMLElement",
  iframe: "HTMLIFrameElement",
  img: "HTMLImageElement",
  input: "HTMLInputElement",
  ins: "HTMLModElement",
  isindex: "HTMLUnknownElement",
  kbd: "HTMLElement",
  keygen: "HTMLUnknownElement",
  label: "HTMLLabelElement",
  legend: "HTMLLegendElement",
  li: "HTMLLIElement",
  link: "HTMLLinkElement",
  listing: "HTMLPreElement",
  main: "HTMLElement",
  map: "HTMLMapElement",
  mark: "HTMLElement",
  marquee: "HTMLMarqueeElement",
  menu: "HTMLMenuElement",
  meta: "HTMLMetaElement",
  meter: "HTMLMeterElement",
  multicol: "HTMLUnknownElement",
  nav: "HTMLElement",
  nextid: "HTMLUnknownElement",
  noscript: "HTMLElement",
  object: "HTMLObjectElement",
  ol: "HTMLOListElement",
  optgroup: "HTMLOptGroupElement",
  option: "HTMLOptionElement",
  output: "HTMLOutputElement",
  p: "HTMLParagraphElement",
  param: "HTMLParamElement",
  picture: "HTMLPictureElement",
  pre: "HTMLPreElement",
  progress: "HTMLProgressElement",
  q: "HTMLQuoteElement",
  rp: "HTMLElement",
  rt: "HTMLElement",
  ruby: "HTMLElement",
  s: "HTMLElement",
  samp: "HTMLElement",
  script: "HTMLScriptElement",
  search: "HTMLElement",
  section: "HTMLElement",
  select: "HTMLSelectElement",
  slot: "HTMLSlotElement",
  small: "HTMLElement",
  source: "HTMLSourceElement",
  spacer: "HTMLUnknownElement",
  span: "HTMLSpanElement",
  strong: "HTMLElement",
  style: "HTMLStyleElement",
  sub: "HTMLElement",
  summary: "HTMLElement",
  sup: "HTMLElement",
  table: "HTMLTableElement",
  tbody: "HTMLTableSectionElement",
  td: "HTMLTableCellElement",
  template: "HTMLTemplateElement",
  textarea: "HTMLTextAreaElement",
  tfoot: "HTMLTableSectionElement",
  th: "HTMLTableCellElement",
  thead: "HTMLTableSectionElement",
  time: "HTMLTimeElement",
  title: "HTMLTitleElement",
  tr: "HTMLTableRowElement",
  track: "HTMLTrackElement",
  u: "HTMLElement",
  ul: "HTMLUListElement",
  var: "HTMLElement",
  video: "HTMLVideoElement",
  wbr: "HTMLElement",
  xmp: "HTMLPreElement",
} satisfies Record<string, string>;

/** SVG tag-to-DOM-type map from TypeScript's `lib.dom.d.ts`. */
const svg_tag_map = {
  a: "SVGAElement",
  animate: "SVGAnimateElement",
  animateMotion: "SVGAnimateMotionElement",
  animateTransform: "SVGAnimateTransformElement",
  circle: "SVGCircleElement",
  clipPath: "SVGClipPathElement",
  defs: "SVGDefsElement",
  desc: "SVGDescElement",
  ellipse: "SVGEllipseElement",
  feBlend: "SVGFEBlendElement",
  feColorMatrix: "SVGFEColorMatrixElement",
  feComponentTransfer: "SVGFEComponentTransferElement",
  feComposite: "SVGFECompositeElement",
  feConvolveMatrix: "SVGFEConvolveMatrixElement",
  feDiffuseLighting: "SVGFEDiffuseLightingElement",
  feDisplacementMap: "SVGFEDisplacementMapElement",
  feDistantLight: "SVGFEDistantLightElement",
  feDropShadow: "SVGFEDropShadowElement",
  feFlood: "SVGFEFloodElement",
  feFuncA: "SVGFEFuncAElement",
  feFuncB: "SVGFEFuncBElement",
  feFuncG: "SVGFEFuncGElement",
  feFuncR: "SVGFEFuncRElement",
  feGaussianBlur: "SVGFEGaussianBlurElement",
  feImage: "SVGFEImageElement",
  feMerge: "SVGFEMergeElement",
  feMergeNode: "SVGFEMergeNodeElement",
  feMorphology: "SVGFEMorphologyElement",
  feOffset: "SVGFEOffsetElement",
  fePointLight: "SVGFEPointLightElement",
  feSpecularLighting: "SVGFESpecularLightingElement",
  feSpotLight: "SVGFESpotLightElement",
  feTile: "SVGFETileElement",
  feTurbulence: "SVGFETurbulenceElement",
  filter: "SVGFilterElement",
  foreignObject: "SVGForeignObjectElement",
  g: "SVGGElement",
  image: "SVGImageElement",
  line: "SVGLineElement",
  linearGradient: "SVGLinearGradientElement",
  marker: "SVGMarkerElement",
  mask: "SVGMaskElement",
  metadata: "SVGMetadataElement",
  mpath: "SVGMPathElement",
  path: "SVGPathElement",
  pattern: "SVGPatternElement",
  polygon: "SVGPolygonElement",
  polyline: "SVGPolylineElement",
  radialGradient: "SVGRadialGradientElement",
  rect: "SVGRectElement",
  script: "SVGScriptElement",
  set: "SVGSetElement",
  stop: "SVGStopElement",
  style: "SVGStyleElement",
  svg: "SVGSVGElement",
  switch: "SVGSwitchElement",
  symbol: "SVGSymbolElement",
  text: "SVGTextElement",
  textPath: "SVGTextPathElement",
  title: "SVGTitleElement",
  tspan: "SVGTSpanElement",
  use: "SVGUseElement",
  view: "SVGViewElement",
} satisfies Record<string, string>;

/** The namespace an element is created in: SVG inside `<svg>`, HTML elsewhere. */
export type ElementNamespace = "html" | "svg";

function lookup(map: Record<string, string>, tag: string): string | undefined {
  return Object.hasOwn(map, tag) ? map[tag] : undefined;
}

/**
 * The DOM type of an element. A tag both namespaces define (`a`, `title`)
 * reads from `namespace`; an SVG-only tag (`path`) is SVG even outside an
 * `<svg>`, since Svelte creates it in the SVG namespace.
 */
export function getElementByTag(element: string, namespace: ElementNamespace = "html"): string {
  if (namespace === "svg") return lookup(svg_tag_map, element) ?? "SVGElement";
  return lookup(tag_map, element) ?? lookup(svg_tag_map, element) ?? "HTMLElement";
}
