import { BACKTICK_REGEX } from "./markdown-format-utils";

const NON_SLUG_CHAR_REGEX = /[^\w\- ]+/g;
const SLUG_SPACE_REGEX = /\s+/g;
const TOC_PLACEHOLDER = "<!-- __TOC__ -->";

/** Mirrors GitHub's heading slugger, including `-1`, `-2`, ... suffixes for duplicates. */
function slugifyHeading(raw: string, seen: Map<string, number>): string {
  const slug = raw
    .toLowerCase()
    .replace(BACKTICK_REGEX, "")
    .replace(NON_SLUG_CHAR_REGEX, "")
    .replace(SLUG_SPACE_REGEX, "-");

  const count = seen.get(slug) ?? 0;
  seen.set(slug, count + 1);
  return count === 0 ? slug : `${slug}-${count}`;
}

export type AppendType = "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "quote" | "p" | "divider" | "raw";

export interface TocLine {
  /** Leading space count; 0 for the top-level (`h2`) entries the TOC currently lists. */
  indent: number;
  raw: string;
}

/**
 * Called after every `append`, with the document itself, so callers can
 * inject extra content (e.g. a summary line under the `h1` title).
 */
export type MarkdownAppendCallback = (type: AppendType, document: MarkdownDocument) => void;

export interface MarkdownDocumentOptions {
  onAppend?: MarkdownAppendCallback;
}

/**
 * Builds one Markdown document in memory. Has no file-system dependency, so
 * the Node writer and the browser entry share it; writing to disk is left to
 * `Writer`.
 *
 * @example
 * ```ts
 * const document = new MarkdownDocument({
 *   onAppend: (type, doc) => {
 *     if (type === "h1") doc.append("quote", "Generated by sveld.");
 *   },
 * });
 * document.append("h1", "Component Index");
 * const markdown = document.end();
 * ```
 */
export class MarkdownDocument {
  public sourceParts: string[] = [];
  public hasToC = false;
  public toc: TocLine[] = [];
  public onAppend?: MarkdownAppendCallback;

  constructor(options: MarkdownDocumentOptions = {}) {
    this.onAppend = options.onAppend;
  }

  public get source(): string {
    return this.sourceParts.join("");
  }

  public appendLineBreaks(): this {
    this.sourceParts.push("\n\n");
    return this;
  }

  public append(type: AppendType, raw?: string): this {
    switch (type) {
      case "h1":
      case "h2":
      case "h3":
      case "h4":
      case "h5":
      case "h6": {
        this.sourceParts.push(`${"#".repeat(Number(type.slice(-1)))} ${raw}`);
        if (this.hasToC && type === "h2") {
          this.toc.push({ indent: 0, raw: raw ?? "" });
        }
        break;
      }
      case "quote":
        this.sourceParts.push(`> ${raw}`);
        break;
      case "p":
        this.sourceParts.push(raw ?? "");
        break;
      case "divider":
        this.sourceParts.push("---");
        break;
      case "raw":
        this.sourceParts.push(raw ?? "");
        break;
    }

    if (type !== "raw") this.appendLineBreaks();
    this.onAppend?.call(this, type, this);
    return this;
  }

  public tableOfContents(): this {
    this.sourceParts.push(TOC_PLACEHOLDER);
    this.hasToC = true;
    this.appendLineBreaks();
    return this;
  }

  public end(): string {
    const source = this.sourceParts.join("");
    if (!this.hasToC) return source;

    const at = source.indexOf(TOC_PLACEHOLDER);
    if (at === -1) return source;

    const seenAnchors = new Map<string, number>();
    const toc = this.toc
      .map(({ indent, raw }) => `${" ".repeat(indent)}- [${raw}](#${slugifyHeading(raw, seenAnchors)})`)
      .join("\n");
    // Not `String#replace`: a heading containing `$&` must be inserted verbatim.
    return source.slice(0, at) + toc + source.slice(at + TOC_PLACEHOLDER.length);
  }
}

/** `MarkdownDocument`'s class name in `sveld/browser` before the Markdown writers merged. */
export class BrowserWriterMarkdown extends MarkdownDocument {}

/** `MarkdownDocument`'s interface name in `sveld/browser` before the Markdown writers merged. */
export type MarkdownWriterBase = MarkdownDocument;
