import { join } from "node:path";
import { convertSvelteExt, createExports } from "../create-exports";
import { info } from "../logger";
import type { ParseCache } from "../parse-cache";
import type { ParsedExports } from "../parse-exports";
import { normalizeSeparators } from "../path";
import type { ComponentDocApi, ComponentDocs } from "../plugin";
import { buildComponentApiDocument } from "./document-model";
import Writer from "./Writer";
import {
  pickEmitOptions,
  propsTypeName,
  serializeEmitOptions,
  type WriteTsDefinitionOptions,
  writeTsDefinition,
} from "./writer-ts-definitions-core";

/**
 * Interface names generated by bundled components that some other bundled
 * component's `@extends`/`@extendProps` targets (e.g. `"ButtonProps"`).
 * Every component whose generated props type name (see `propsTypeName`,
 * templated by `typesOptions.typeNames.props`) appears here must keep its
 * props type exported even when `typesOptions.exportTypes` says otherwise,
 * since the extending component emits `import type { ButtonProps } from
 * "./Button.svelte"` and that import breaks if the type stops being exported.
 */
function collectExtendsTargetInterfaces(components: ComponentDocApi[]): Set<string> {
  const targets = new Set<string>();
  for (const component of components) {
    if (component.extends) targets.add(component.extends.interface);
  }
  return targets;
}

/**
 * Whether `exportTypes` would already export the props type on its own,
 * without any `forceExportProps` override. `forceExportProps` is only
 * meaningful (and only added to the per-component options, and thus the
 * cache key) when it actually flips the outcome - otherwise every component
 * would get a `forceExportProps: false` fingerprint baked into its cache key
 * for no behavioral reason, invalidating caches pointlessly on every run.
 */
function propsExportedByDefault(exportTypes: WriteTsDefinitionOptions["exportTypes"]): boolean {
  if (exportTypes === undefined || exportTypes === true) return true;
  if (exportTypes === false) return false;
  return exportTypes.props ?? true;
}

/** The context `typesOptions.transform` receives alongside the generated text. */
export type TransformContext =
  | { kind: "component"; component: ComponentDocApi; filePath: string }
  | { kind: "index"; filePath: string };

/**
 * Runs `typesOptions.transform` (a no-op passthrough when unset) over
 * generated `.d.ts` text, called after the generated-text cache lookup so a
 * changed transform can never serve stale cached output. A transform that
 * throws, or resolves to something other than a string, fails the run with a
 * `sveld:`-prefixed error naming the file - same shape as the writer-failure
 * error in `src/writer/registry.ts`.
 */
async function applyTransform(
  transform: WriteTsDefinitionsOptions["transform"],
  text: string,
  context: TransformContext,
): Promise<string> {
  if (!transform) return text;
  try {
    const result = await transform(text, context);
    if (typeof result !== "string") {
      throw new TypeError(`must return a string, got ${typeof result}`);
    }
    return result;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(`sveld: typesOptions.transform failed for "${context.filePath}": ${message}`, { cause: error });
  }
}

/**
 * Re-export browser-compatible functions from core module.
 *
 * These functions are exported from the core TypeScript definitions writer
 * to provide a browser-compatible API surface. The core module contains the
 * actual implementation logic.
 *
 * @see {@link ./writer-ts-definitions-core} for the core implementation
 */
export { formatTsProps, getContextDefs, getTypeDefs, writeTsDefinition } from "./writer-ts-definitions-core";

/**
 * @example
 * ```ts
 * const options: WriteTsDefinitionsOptions = {
 *   outDir: "./dist",
 *   inputDir: "./src",
 *   preamble: "// Generated by sveld\n",
 *   exports: { ... }
 * };
 * ```
 */
export interface WriteTsDefinitionsOptions extends WriteTsDefinitionOptions {
  outDir: string;
  /** @internal Resolved from `entry` and always injected by the caller (`plugin.ts`); not user-configurable via `typesOptions`. */
  inputDir: string;
  preamble: string;
  /** @internal Always computed from the parsed bundle and injected by the caller; not user-configurable via `typesOptions`. */
  exports: ParsedExports;
  /** @internal Report resolved paths instead of writing. Always set by the caller from `sveld --dry-run`. */
  dryRun?: boolean;
  /**
   * @internal Reuses generated `.d.ts` text across runs for components whose
   * source (and every emit option from `serializeEmitOptions`) hasn't
   * changed. Requires `resolvedPathByFilePath` to key lookups; both come
   * from `GenerateBundleResult`.
   */
  cache?: ParseCache;
  /** @internal See `cache`. Lookups use `component.filePath`. */
  resolvedPathByFilePath?: Map<string, string>;
  /**
   * Post-processes each generated file's text before it is written. Runs
   * after the generated-text cache, so it applies on every run. Config file
   * or `sveld()` only.
   */
  transform?: (text: string, context: TransformContext) => string | Promise<string>;
}

/**
 * @example
 * ```ts
 * await writeTsDefinitions(components, {
 *   outDir: "./dist",
 *   inputDir: "./src",
 *   preamble: "// Generated\n",
 *   exports: { ... }
 * });
 * // Creates dist/Button.d.ts, dist/Input.d.ts, dist/index.d.ts
 * ```
 */
export default async function writeTsDefinitions(components: ComponentDocs, options: WriteTsDefinitionsOptions) {
  const ts_base_path = join(process.cwd(), options.outDir, "index.d.ts");
  const writer = new Writer({ dryRun: options.dryRun });
  const indexDTs = options.preamble + createExports(options.exports);

  const document = buildComponentApiDocument(components);
  const extendsTargetInterfaces = collectExtendsTargetInterfaces(document.components);
  const baseEmitOptions = pickEmitOptions(options);
  const writePromises = document.components.map(async (component) => {
    const ts_filepath = convertSvelteExt(join(options.outDir, component.filePath));
    const relativeFilePath = normalizeSeparators(convertSvelteExt(component.filePath));
    const resolvedPath = options.resolvedPathByFilePath?.get(component.filePath);
    const emitOptions =
      extendsTargetInterfaces.has(propsTypeName(component.moduleName, options.typeNames)) &&
      !propsExportedByDefault(baseEmitOptions.exportTypes)
        ? { ...baseEmitOptions, forceExportProps: true }
        : baseEmitOptions;
    const cacheKey = serializeEmitOptions(emitOptions);
    let text = resolvedPath ? options.cache?.getGeneratedText(resolvedPath, cacheKey) : undefined;
    if (text === undefined) {
      text = writeTsDefinition(component, emitOptions);
      if (resolvedPath) options.cache?.setGeneratedText(resolvedPath, cacheKey, text);
    }
    const transformedText = await applyTransform(options.transform, text, {
      kind: "component",
      component,
      filePath: relativeFilePath,
    });
    await writer.write(ts_filepath, transformedText);
  });

  const indexWritePromise = (async () => {
    const transformedIndexDts = await applyTransform(options.transform, indexDTs, {
      kind: "index",
      filePath: "index.d.ts",
    });
    await writer.write(ts_base_path, `${transformedIndexDts}\n`);
  })();

  await Promise.all([...writePromises, indexWritePromise]);

  if (!options.dryRun) info("created TypeScript definitions.");
}
