import { join } from "node:path";
import { convertSvelteExt, createExports } from "../create-exports";
import type { ParsedExports } from "../parse-exports";
import type { ComponentDocs } from "../plugin";
import { createTypeScriptWriter } from "./Writer";
import { writeTsDefinition } from "./writer-ts-definitions-core";

/**
 * Re-export browser-compatible functions from core module.
 *
 * These functions are exported from the core TypeScript definitions writer
 * to provide a browser-compatible API surface. The core module contains the
 * actual implementation logic.
 *
 * @see {@link ./writer-ts-definitions-core} for the core implementation
 */
export {
  formatTsProps,
  getContextDefs,
  getTypeDefs,
  writeTsDefinition,
} from "./writer-ts-definitions-core";

/**
 * Options for writing TypeScript definition files.
 *
 * @property outDir - The output directory where `.d.ts` files will be written
 * @property inputDir - The input directory containing source components
 * @property preamble - Text to prepend to the main `index.d.ts` file
 * @property exports - Parsed export information for generating the index file
 *
 * @example
 * ```ts
 * const options: WriteTsDefinitionsOptions = {
 *   outDir: "./dist",
 *   inputDir: "./src",
 *   preamble: "// Generated by sveld\n",
 *   exports: { ... }
 * };
 * ```
 */
export interface WriteTsDefinitionsOptions {
  outDir: string;
  inputDir: string;
  preamble: string;
  exports: ParsedExports;
}

/**
 * Writes TypeScript definition files for all parsed Svelte components.
 *
 * Generates individual `.d.ts` files for each component and a main `index.d.ts`
 * file that exports all components. Uses a TypeScript writer to handle file
 * I/O operations efficiently.
 *
 * @param components - Map of component module names to their parsed documentation
 * @param options - Configuration options for writing definitions
 * @returns A promise that resolves when all files have been written
 *
 * @example
 * ```ts
 * const components = new Map([
 *   ["Button", { filePath: "Button.svelte", props: [...], ... }],
 *   ["Input", { filePath: "Input.svelte", props: [...], ... }]
 * ]);
 *
 * await writeTsDefinitions(components, {
 *   outDir: "./dist",
 *   inputDir: "./src",
 *   preamble: "// Generated\n",
 *   exports: { ... }
 * });
 *
 * // Creates:
 * // - dist/Button.d.ts
 * // - dist/Input.d.ts
 * // - dist/index.d.ts
 * ```
 */
export default async function writeTsDefinitions(components: ComponentDocs, options: WriteTsDefinitionsOptions) {
  const ts_base_path = join(process.cwd(), options.outDir, "index.d.ts");
  const writer = createTypeScriptWriter();
  const indexDTs = options.preamble + createExports(options.exports);

  const writePromises = Array.from(components).map(async ([_moduleName, component]) => {
    const ts_filepath = convertSvelteExt(join(options.outDir, component.filePath));
    await writer.write(ts_filepath, writeTsDefinition(component));
  });

  await Promise.all([...writePromises, writer.write(ts_base_path, indexDTs)]);

  console.log("created TypeScript definitions.");
}
